export const TIME_ENTRY_SERVICE_COUNTER_PERIOD_IN_MILLISECONDS = 1000;
export const TIME_ENTRY_SERVICE_WATCHER_PERIOD_IN_MILLISECONDS = 5000;

export const TimeEntryServiceConstants = {
  counterPeriod: TIME_ENTRY_SERVICE_COUNTER_PERIOD_IN_MILLISECONDS,
  watcherPeriod: TIME_ENTRY_SERVICE_WATCHER_PERIOD_IN_MILLISECONDS
};
