export const TIMER_SERVICE_SECOND_PERIOD_IN_MILLISECONDS = 1000;
export const TIMER_SERVICE_API_CALL_PERIOD_IN_MILLISECONDS = 5000;

export const TimerServiceConstants = {
  secondPeriod: TIMER_SERVICE_SECOND_PERIOD_IN_MILLISECONDS,
  apiCallPeriod: TIMER_SERVICE_API_CALL_PERIOD_IN_MILLISECONDS
};
